version: '3.8'

services:
  postgres:
    image: mdillon/postgis:latest
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=ze
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=pg@123
    volumes:
      - pg-volume-data:/var/lib/postgresql/data
  
volumes:
  pg-volume-data:
