name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm install
          npm run test:unit
          
  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASS: ${{secrets.DATABASE_PASS}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ze-challenge-marcos"
          heroku_email: "ze-challenge-marcos@gmail.com"
          healthcheck: "https://ze-challenge-marcos.herokuapp.com/health"
